### ISSUE TITLE
Cambio de nomenclatura "destiny" debe ser "target"

### ISSUE THREAD

**Issue by juacas** [UNIMOODLE/moodle-local_coursetransfer#11]
El término destiny se está usando como "target".
Realmente "destiny" significa "futuro", "predestinación".

De cara a la publicación del software, es recomendable refactorizar ese término para usarlo correctamente y que no manche la reputación de los programadores.

**Comment by xpazv** [comment]
En revisión

**Comment by xpazv** [comment]
En proceso de refactorización.

**Comment by juacas** [comment]
Correcto.
Hay que implementar el upgrade.php para que el cambio sea transparente entre versiones

**Comment by xpazv** [comment]
Asi lo estamos afrontando @juacas era solo para hacer notar el alcance de la refactorización, ya que en vuestro caso, disponeis de una versión antigua, y un upgrade tan complejo puede ser bastante problemático.

**Comment by juacas** [comment]
Un cambio de nombre de una columna de BBDD y el renombrado de variables en el código debería ser totalmente transparente para las actualizaciones. Nunca me he encontrado con problemas en estas operaciones.
El único punto problemático podría ser la comunicación entre nodos con versiones distintas del plugin debido a la codificación de los mensajes (si es que aparece "destiny" ahí).

No obstante, avisad a las universidades que están probando el módulo para identificar esos problemas.

**Comment by xpazv** [comment]
Aparece en diferentes ámbitos, de ahí el riesgo si en un mismo entorno, conviven diferentes versiones.

Avisaremos a las universidades, tal y como indicas.

**Comment by xpazv** [comment]
Ya se ha implementado. Estamos realizando pruebas de todo el flujo completo, de nuevo, antes de subir la version correspondiente al repositorio @juacas
