### ISSUE TITLE
Problemas para publicar el plugin como Administration Tool.

### ISSUE THREAD

**Issue by juacas** [UNIMOODLE/moodle-local_coursetransfer#12]
En el directorio de plugins la categoría "Administration tools" tienen que instalarse en el espacio "tool" en lugar de "local".
El nivel de "maturity" está marcado en ALPHA. ¿Es correcto? Se supone que en el momento de la entrega el producto debe ser al menos ReleaseCandidate.

Por favor, comentemos estos puntos y tomemos una decisión conjunta para poder pasarlo al directorio.

**Comment by xpazv** [comment]
Lo tratamos conjuntamente en una reunión @juacas 

En cualquier caso, el plugin debe estar clasificado como **other tools** ya que contiene funcionalidades para profesores y en contextos de curso. Por este motivo, no se clasifica como herramienta de administración (Admin tool)

Respecto al nivel de _maturity_ por nuestra parte siempre lo calificamos como ALPHA, hasta quien debe validarlo da su visto bueno, y en ese caso, pasa a ReleaseCandidate.
