### ISSUE TITLE
Code prechecks errors

### ISSUE THREAD

**Issue by juacas** [UNIMOODLE/moodle-local_coursetransfer#13]
La validación de moodle plugins da algunos errores:
Code prechecks:
phplint phpcs81 | 0 js20 | 119 css phpdoc savepoint thirdparty grunt1 | 1 shifter mustache50 | 0 gherkin

Por favor repasad el validador CodeChecker.

**Comment by xpazv** [comment]
En revisión.

**Comment by xpazv** [comment]
¿Nos podrías aportar @juacas el fichero HTML resultante del análisis? Estamos observando que ciertos prechecks no dan cobertura a implementaciones realizadas para el proyecto.
