### ISSUE TITLE
Functionality 4. Admin plug-in to restore a course between platforms using functionalities 1 and 2 

### ISSUE THREAD

**Issue by mapemo4** [UNIMOODLE/moodle-local_coursetransfer#20]
Bugs reported on the latest published version of the plugin on github (2024031800) in UVa

When restoring courses, courses selected using the checkbox remain marked in the session between different requests*.

Is this cached? With this problem, even if you perform other actions in Moodle (these actions have nothing to do with the plugin) 

Steps to reproduce
If you use the plugin again and  it will go to select other courses, so, the previous ones are still marked and it is necessary unchecked them (you can't sometimes find them among the 350 course pages).  
Actual Result
-The same situation happens with other different restore options (merge, delete content, etc). 
-When restoring categories, the same thing happens, the previously restored category remains selected.
-It is necessary to resets the form or the memory where  information is stored. 
- For that,  you must be sure that between requests the courses checkboxes are unchecked previosly:
cache, $_SESSION PHP.

Expected result 

Solve the last problems mentioned

**Comment by xpazv** [comment]
Under review

**Comment by mapemo4** [comment]
@xpazv Preguntar por este bug?

**Comment by xpazv** [comment]
Should be fixed in last version available.
