### ISSUE TITLE
Functionality 5. Teacher plug-in to restore teacher courses between platforms controlled by a moodle capabilities set

### ISSUE THREAD

**Issue by mapemo4** [UNIMOODLE/moodle-local_coursetransfer#21]
Bugs reported on the latest published version of the plugin on github (2024031800)

Teacher UI

**1 Review functionality to restore courses when the teacher does not have the capability to restore with user data.** 

Steps to reproduce:
Home
More> Restore Remote Course> Restore Remote Course >To restore a course from another platform, you must first select the site where the original course is located.

Expected Result

A teacher should be able to restore a course even if the course has user data but a teacher should not have the capability to achive with the user data restoration.

- If a university requires that a teacher has the capability to restore a course with user data, then they should ensure that they restore with or without user data.
 If the teacher lacks this capability, they should just have the capability to restore the contents.

 - At UVA, it is customary for a teacher to have the capability to restore a source course that contains user data. However, it is imperative that the restoration does not contain any user data.

The desirable thing in our case is that we do not give the capability to restore a remote course with user data although that it should not prevent a teacher from restoring the course with its content of activities and resources.

**2. Teacher capabilities**

The permissions/capabilities issue is related to the courses a teacher should see.  A teacher should not see all the origin courses, so a teacher should only see the courses in which he/she is enrolled as a teacher:

Steps to reproduce:
Home
More> Restore Remote Course> Restore Remote Course >To restore a course from another platform, you must first select the site where the original course is located. Click Next. > Restore Remote Course. A screen shows Restore Remote Course - Select the course to restore.

Actual result:

Now, a screen appears with a list of available courses.

It seems to be the origin list courses

Expected result

Check Permissions if the teacher is enrolled in these courses and show these courses in this screen.

**Comment by xpazv** [comment]
Under development

**Comment by xpazv** [comment]
Point 2 will be included in next version

**Comment by mapemo4** [comment]
@xpazv en cual version?

**Comment by xpazv** [comment]
Last version available

**Comment by mapemo4** [comment]
El profesor con la version 1.1 ve solamente sus cursos. Este error esta resuelto.

**Comment by mapemo4** [comment]
related to #27
