### ISSUE TITLE
Functionality 4. Admin plug-in restoring a remote course using functionalities 1 and 2

### ISSUE THREAD

**Issue by mapemo4** [UNIMOODLE/moodle-local_coursetransfer#22]
After updating the development branch in 4.1 and 3.11 to yesterday's version on the 18th in UVA, we have carried out a small battery of tests to restore courses as admin. We have encountered several problems:

As an administrator, restoring a remote course does not give us the following options:

1) Select whether to restore with user data.
2) Remove roles from target course.
3) Whether or not to delete the source course.

 Of the 3 options discussed, the most important for us is to be able to restore a course with user data. 
The other two options are less important, but they should also be able to do too.

Steps to reproduce:
Site Admin> Courses>Manage courses and categories

![image003](https://github.com/UNIMOODLE/moodle-local_coursetransfer/assets/157824055/9617ae0a-04c9-423f-8bb8-ee447fb71f2c)

![image005](https://github.com/UNIMOODLE/moodle-local_coursetransfer/assets/157824055/3202fa9e-84f6-4124-90ed-cb5a6e2b936d)

![image004](https://github.com/UNIMOODLE/moodle-local_coursetransfer/assets/157824055/73810d2c-aa54-412b-8ddd-e5e70002b77a)

Actual Result:
An error occurs if you proceed to restore from course and category administration.
The following error displayed is "11001: It is necessary to provide a name for the category"

**Comment by xpazv** [comment]
Under review.

**Comment by xpazv** [comment]
Fixed in latest version.
