### ISSUE TITLE
Unable to restore a course or category - from the tab in admin->plugin->Restore remote courses or categories

### ISSUE THREAD

**Issue by Nitr0z** [UNIMOODLE/moodle-local_coursetransfer#24]
![image](https://github.com/UNIMOODLE/moodle-local_coursetransfer/assets/48621976/2e03263e-f30c-4605-8f79-380df570725a)

**Comment by Nitr0z** [comment]
I tested on several platforms in one direction or the other, I got the same error all the time. Platforms in 4.1 LTS

**Comment by xpazv** [comment]
Fixed in latest version available.
