### ISSUE TITLE
Listado de categorías

### ISSUE THREAD

**Issue by tmas0** [UNIMOODLE/moodle-local_coursetransfer#26]
Buenas,

Al ir a restaurar una categoría, solo se están viendo las categorías visibles. Entendemos que es un error, ya que si hay categorías ocultas que se quieren restaurar, no aparecen en el listado.

Se deberían visualizar las categorías a las cuales se tiene acceso, estén o no ocultas.

Un saludo

**Comment by xpazv** [comment]
No puede ser considerado un bug, pues no se trata de un error de funcionamiento.

La implementación actual es la manera en que un admin de origen pueda "ocultar" categorias para que no se restauren, y por lo tanto se ha respetado ese enfoque.

Se propone añadir un setting, al plugin, para mostrar categorias ocultas, y que el administrador de origen decida cómo proceder, pero mostrar también categorias ocultas puede suponer un riesgo, sea controlado por permisos en ambos lados o por setting.

**Comment by mapemo4** [comment]
related #25
related #19
