### ISSUE TITLE
Error (exception) when cloning category between sites

### ISSUE THREAD

**Issue by sollericos** [UNIMOODLE/moodle-local_coursetransfer#28]
Context:
* Both sites: 4.1.11 (Build: 20240610)
* Same admin user on both sites (id, username, email, etc.)
* Plugin version: 1.1.1 (2024061800)

I can see category listing (only visible ones, not good, see issue #26 ). Following message is thrown in the fourth step:

`Error (100083): Exception - local_coursetransfer\factory\category::create(): Argument #2 ($idnumber) must be of type string, null given, called in [dirroot]/local/coursetransfer/classes/coursetransfer.php on line 650`

Do you need more details?

**Comment by xpazv** [comment]
Fixed in latest version.
