### ISSUE TITLE
Functionality 4. Admin plug-in to restore courses and categories between platforms using functionalities 1 and 2 - Manage courses and categories Screen

### ISSUE THREAD

**Issue by mapemo4** [UNIMOODLE/moodle-local_coursetransfer#3]
As admin:
Site administration > Courses>Manage courses and categories

There exists another remote category restoration screen available where it can be selected to courses. This screen is located in course management. Nonetheless, this particular screen exhibits certain shortcomings and errors, such as the inability to mark all courses in the category at once. If a course is selected or unchecked, or if multiple courses are selected simultaneously. In fact, it is detected that the initial marking is being selected too. Finally, it displays the error message -"100012"- and does not allow running the restoration.
![SiteAdministration-Manage courses-](https://github.com/UNIMOODLE/moodle-local_coursetransfer/assets/157824055/8b737388-16dc-4ba0-9a2b-424eed84f21b)

![Existe otra pantalla de restauración de categorías remota error](https://github.com/UNIMOODLE/moodle-local_coursetransfer/assets/157824055/4ef56958-c268-402b-b388-3630e512abec)

![error](https://github.com/UNIMOODLE/moodle-local_coursetransfer/assets/157824055/ea8ff9f1-15ad-4668-88c8-788e91c9a6c3)

**Comment by mapemo4** [comment]
Steps to reproduce:

As an admin role:
Go to Site administration > Courses>Manage courses and categories

To restore courses from another platform, you must first select the site where the original courses are located. Then Select origin site.

Actual result:
The error message is: " (11001): Category name is required".

Expected result

The restoration has been carried out successfully.

**Comment by xpazv** [comment]
In review.

**Comment by mapemo4** [comment]
1.- Course selection/deselection error:

Steps to reproduce:

Site Administration>Courses>Manage courses and categories>Origin restore Category. Select the courses categories to restore - Restore Remote Courses in Category

To restore courses from another platform, you must first select the site where the original courses are located. > Select origin site

Restore Remote Courses in Category

Select the courses you want to restore from the chosen category

This screen displays a list of courses from the source category that need to be checked to restore. 

To continue, check the box button and select the courses to restore. After that, check that the courses are the ones you want to restore  and make sure using the back button. 

Now it displays the error message “Error (11001): Category name is required“

**Comment by mapemo4** [comment]
It would be necessary an improvement in this screen. There is a list of courses if there are many, it would be good if there was a check box to mark all of them.
It can be quite difficult to locate a course when there are numerous pages present. It should be necessary to add the page and a search filter by name and idnumber to locate the course.

**Comment by mapemo4** [comment]
It would be necessary an improvement in this screen. There is a list of courses if there are many, it would be good if there was a check box to mark all of them.
It can be quite difficult to locate a course when there are numerous pages present. It should be necessary to add the page and a search filter by name and idnumber to locate the course.

**Comment by xpazv** [comment]
We are evaluating the improvement suggested.

**Comment by xpazv** [comment]
Course search included in next version.
