### ISSUE TITLE
Exception when restoring courses

### ISSUE THREAD

**Issue by LuksAO** [UNIMOODLE/moodle-local_coursetransfer#31]
When we try to restore a course, either from the course's UI or the admin's, we get the following exception when we press "Next" on the first step:

```
Excepción - local_coursetransfer\output\renderer::get_html_paging_bar(): Argument #1 ($paging) must be of type stdClass, null given, called in [dirroot]/local/coursetransfer/classes/output/renderer.php on line 122
```

I tested the plugin with two environments with just one category and one course and it worked, so I guess this is related to our courses/categories tree struct with hidden items, we have this struct:

![image](https://github.com/UNIMOODLE/moodle-local_coursetransfer/assets/43584301/eab3beae-8f33-4a2e-bbfd-ebaa4c1d40e7)

**Oddly when we show the second category the error disappears.** Maybe this is related with #26 ?

**Comment by xpazv** [comment]
Please, indicate Moodle and PHP version.

**Comment by xpazv** [comment]
Fixed in latest version.
