### ISSUE TITLE
Functionality 4. Admin plug-in for restoring courses and categories across platforms using functionalities 1 and 2. Settings, error message: 120001 and paginating

### ISSUE THREAD

**Issue by mapemo4** [UNIMOODLE/moodle-local_coursetransfer#5]
1. In both moodles, the source and destination settings must be identical.  
  Given 2 moodle according to this use case:

  A - destination (new Moodle with empty courses).
  B - origin (old Moodle with previous period courses.)

For the plugin to work in moodle A, it must be set to origin of moodle B and also A itself.
For the administrator, this is not a problem, but for the teacher role, when selecting a source, the two Moodle appear and itself should be hidden as a source.

3. If it takes a long time to respond, the WS displays the error message: -120001- because there is a limit of 20 Sg in classes/api/request.php. This value is agreed to be included as a parameter. At the moment, it is changed in the code to 2000 seconds. It remains to investigate this delay problem may be from the moodle preproduction. They are assigned an admin account in the UV moodle.   

4. When restoring courses as an administrator, paginating is necessary to prevent the browser from running out of memory due to the number of courses in the drop-down list.

**Comment by xpazv** [comment]
Point 2 tested with latest version, using Moodle 4.1.2 and Moodle 3.11

The bug is fixed.

**Comment by mapemo4** [comment]
> Point 2 tested with latest version, using Moodle 4.1.2 and Moodle 3.11
> 
> The bug is fixed.

We are using Moodle 4.1.9

**Comment by mapemo4** [comment]
> Pagination added in last version.

 To locate a course can be quite difficult when there are numerous pages present.

**Comment by mapemo4** [comment]
It can be quite difficult to locate a course when there are numerous pages present.
A search engine is required to locate the course.

**Comment by xpazv** [comment]
> It can be quite difficult to locate a course when there are numerous pages present.
A search engine is required to locate the course.

We can evaluate, in a separete issue, the implementation of a non reactive course search engine feature as an enchancement
