### ISSUE TITLE
Functionality 4. Admin plug-in to restore courses and categories between platforms using functionalities 1 and 2 -  Standard Moodle Cases and Moodle 3.11

### ISSUE THREAD

**Issue by mapemo4** [UNIMOODLE/moodle-local_coursetransfer#6]
Finally, these errors were identified: 

-Errors in restorations with standard Moodle cases such as enrol_database, and manualenrol_ or similar. 
-Error 16011 with Moodle 3.11 and similar: This plugin must support these cases given its functional purpose.

**Comment by xpazv** [comment]
In review.
