### ISSUE TITLE
Functionality 5. Teacher plug-in to restore teacher courses between platforms controlled by a moodle capabilities set   

### ISSUE THREAD

**Issue by mapemo4** [UNIMOODLE/moodle-local_coursetransfer#7]
This functionality as a teacher:

5.1 Both moodles must have the same source and destination settings. Try to hide the source teacher from the target moodle, as it may be misleading, you could add a parameter.
5.2 Restoring a category at destination is done correctly, but it is labelled as a 'New category' when it should have the same name and ID number as the source category.

**Comment by mapemo4** [comment]
There is a new permission to review as a teacher role: 
-Teacher capabilities
The permissions/capabilities issue is related to the courses a teacher should see. We attach this screenshot with the capabilities. A teacher should not see all the origin courses, so a teacher should only see the courses in which he is enrolled as a teacher:
![teacher_capabilities_set](https://github.com/UNIMOODLE/moodle-local_coursetransfer/assets/157824055/84e2a13f-def1-4c7e-b9d8-06899d713c29)

@xpazv Steps to reproduce:
Home
 More> Restore Remote Course> Restore Remote Course >To restore a course from another platform, you must first select the site where the original course is located.

Then Check Permissions if the teacher is enrolled in these courses.

**Comment by xpazv** [comment]
Under review. Will be fixed in next version uploaded
