### ISSUE TITLE
Functionality 8. Ad-hoc tasks

### ISSUE THREAD

**Issue by mapemo4** [UNIMOODLE/moodle-local_coursetransfer#9]
1- It is verified that the ad-hoc tasks are processed correctly. 
2- Note that when the task fails, they are recorded in the ad-hoc task table indefinitely.

**Comment by mapemo8** [comment]
According to your comment, "There are several causes of failure (backup, a transfer (mbz) or restore on target) in the three queued operations or tasks. When Moodle attempts to cron the task, it will increment the next runtime and generate a new timestamp for the next execution"
We have tested  when deleting a course the ad hoc task fails with the following error:
There is an error in ad hoc task: local_coursetransfer\task\remove_course_task,Argument
 1 passed to mod_bigbluebuttonbn\instance::__construct() must be a
cm_info instance, null given, called on
 /var/moodlenew/WEB/www/mod/bigbluebuttonbn/class
 Backtracking:
 * line 139 of /mod/bigbluebuttonbn/classes/instance.php: call to
 mod_bigbluebuttonbn\instance->__construct()
 * line 160 of /mod/bigbluebuttonbn/lib.php: call to
 mod_bigbluebuttonbn\instance::get_from_instanceid()
 * line 5207 of /lib/moodlelib.php: call to bigbluebuttonbn_delete_instance()
 * line 5070 of /lib/moodlelib.php: call to remove_course_contents()
 * line 1247 of /course/externallib.php: call to delete_course()
 * line 87 of /local/coursetransfer/classes/task/remove_course_task.php:
 call core_course_external::delete_courses()
 * line 367 of /lib/cronlib.php: call to
 local_coursetransfer\task\remove_course_task->execute()
 * line 198 of /lib/cronlib.php: call to cron_run_inner_adhoc_task()
 * line 76 of /lib/cronlib.php: call to cron_run_adhoc_tasks()
 * line 178 of /admin/cli/cron.php: call to cron_run()

We ran 1 ad hoc tasks found on Mon, 25 Mar 2024 13:37:01 +0100
 Cron script completed successfully
 Cron completed at 13:37:03. Memory used 51.8 MB. The execution took 1.978569 seconds

**Comment by xpazv** [comment]
This error happens only with the big blue button module or it happens with any module present?

Could you please provide a copy of the course backup, so we can reproduce the error @mapemo4 ?

**Comment by mapemo4** [comment]
The error happens using the big blue button module in moodlerec @xpazv

**Comment by xpazv** [comment]
What is moodlerec @mapemo4 ?

**Comment by xpazv** [comment]
We will try to reproduce it, as the error comes specifically from big blue button module, which is not part of the development, so we must check first if we have margin to fix it, because we use the delete_course moodle standard function.

If you can provide a course backup file, without user data, it would help us to reproduce and debug the issue.

**Comment by mapemo4** [comment]
> What is moodlerec @mapemo4? Which Moodle version did you use when getting the error?

The Moodle version is 4.1.9.

**Comment by mapemo4** [comment]
Al borrar un curso la adhoc task falla:

Adhoc task failed: local_coursetransfer\task\remove_course_task,Argument 
1 passed to mod_bigbluebuttonbn\instance::__construct() must be an 
instance of cm_info, null given, called in 
/var/moodlenew/WEB/www/mod/bigbluebuttonbn/class
Backtrace:
* line 139 of /mod/bigbluebuttonbn/classes/instance.php: call to 
mod_bigbluebuttonbn\instance->__construct()
* line 160 of /mod/bigbluebuttonbn/lib.php: call to 
mod_bigbluebuttonbn\instance::get_from_instanceid()
* line 5207 of /lib/moodlelib.php: call to bigbluebuttonbn_delete_instance()
* line 5070 of /lib/moodlelib.php: call to remove_course_contents()
* line 1247 of /course/externallib.php: call to delete_course()
* line 87 of /local/coursetransfer/classes/task/remove_course_task.php: 
call to core_course_external::delete_courses()
* line 367 of /lib/cronlib.php: call to 
local_coursetransfer\task\remove_course_task->execute()
* line 198 of /lib/cronlib.php: call to cron_run_inner_adhoc_task()
* line 76 of /lib/cronlib.php: call to cron_run_adhoc_tasks()
* line 178 of /admin/cli/cron.php: call to cron_run()

Ran 1 adhoc tasks found at Mon, 25 Mar 2024 13:37:01 +0100
Cron script completed correctly
Cron completed at 13:37:03. Memory used 51.8 MB.
Execution took 1.978569 seconds

> We will try to reproduce it, as the error comes specifically from big blue button module, which is not part of the development, so we must check first if we have margin to fix it, because we use the delete_course moodle standard function.
> 
> If you can provide a course backup file, without user data, it would help us to reproduce and debug the issue.

An example:
When deleting a course, the ad hoc task fails:

Adhoc task failed: local_coursetransfer\task\remove_course_task,Argument 
1 passed to mod_bigbluebuttonbn\instance::__construct() must be an 
instance of cm_info, null given, called in 
/var/moodlenew/WEB/www/mod/bigbluebuttonbn/class
Backtrace:
* line 139 of /mod/bigbluebuttonbn/classes/instance.php: call to 
mod_bigbluebuttonbn\instance->__construct()
* line 160 of /mod/bigbluebuttonbn/lib.php: call to 
mod_bigbluebuttonbn\instance::get_from_instanceid()
* line 5207 of /lib/moodlelib.php: call to bigbluebuttonbn_delete_instance()
* line 5070 of /lib/moodlelib.php: call to remove_course_contents()
* line 1247 of /course/externallib.php: call to delete_course()
* line 87 of /local/coursetransfer/classes/task/remove_course_task.php: 
call to core_course_external::delete_courses()
* line 367 of /lib/cronlib.php: call to 
local_coursetransfer\task\remove_course_task->execute()
* line 198 of /lib/cronlib.php: call to cron_run_inner_adhoc_task()
* line 76 of /lib/cronlib.php: call to cron_run_adhoc_tasks()
* line 178 of /admin/cli/cron.php: call to cron_run()

Ran 1 adhoc tasks found at Mon, 25 Mar 2024 13:37:01 +0100
Cron script completed correctly
Cron completed at 13:37:03. Memory used 51.8 MB.
Execution took 1.978569 seconds

**Comment by mapemo4** [comment]
> > We will try to reproduce it, as the error comes specifically from big blue button module, which is not part of the development, so we must check first if we have margin to fix it, because we use the delete_course moodle standard function.
> > If you can provide a course backup file, without user data, it would help us to reproduce and debug the issue.

An example:
When deleting a course, the ad hoc task fails:

Adhoc task failed: local_coursetransfer\task\remove_course_task,Argument 
1 passed to mod_bigbluebuttonbn\instance::__construct() must be an 
instance of cm_info, null given, called in 
/var/moodlenew/WEB/www/mod/bigbluebuttonbn/class
Backtrace:
* line 139 of /mod/bigbluebuttonbn/classes/instance.php: call to 
mod_bigbluebuttonbn\instance->__construct()
* line 160 of /mod/bigbluebuttonbn/lib.php: call to 
mod_bigbluebuttonbn\instance::get_from_instanceid()
* line 5207 of /lib/moodlelib.php: call to bigbluebuttonbn_delete_instance()
* line 5070 of /lib/moodlelib.php: call to remove_course_contents()
* line 1247 of /course/externallib.php: call to delete_course()
* line 87 of /local/coursetransfer/classes/task/remove_course_task.php: 
call to core_course_external::delete_courses()
* line 367 of /lib/cronlib.php: call to 
local_coursetransfer\task\remove_course_task->execute()
* line 198 of /lib/cronlib.php: call to cron_run_inner_adhoc_task()
* line 76 of /lib/cronlib.php: call to cron_run_adhoc_tasks()
* line 178 of /admin/cli/cron.php: call to cron_run()

Ran 1 adhoc tasks found at Mon, 25 Mar 2024 13:37:01 +0100
Cron script completed correctly
Cron completed at 13:37:03. Memory used 51.8 MB.
Execution took 1.978569 seconds

**Comment by xpazv** [comment]
The error message seems to be caused by a Moodle 4.1.2 minor bug @mapemo4 

Please, check https://tracker.moodle.org/browse/MDL-77924

Could you please confirm if the bigbluebutton plugin is disabled in that platform?

**Comment by mapemo4** [comment]
> The error message seems to be caused by a Moodle 4.1.2 minor bug @mapemo4
> 
> Please, check https://tracker.moodle.org/browse/MDL-77924
> 
> Could you please confirm if the bigbluebutton plugin is disabled in that platform?

Yes, we actually have this plugin disabled.
We are going to enable it. Our Moodle version is 4.1.9.

**Comment by mapemo4** [comment]
> Can we close the issue as it is not related with the plugin?

Yes, @xpazv Thank you
